### ISSUE TITLE
mask process - datacube for replacement

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes#176] opened 2020-07-08 09:30 UTC
Comparing the if and mask processes:
- The if allows for any type, including datacubes, for the accept and reject parameters
- The mask process allows datacubes only for data but not for replacement (which could be seen as the accept and reject parameter of the if)

Enhancement proposed: allow datacubes also for the replacement field for the mask process.

Does it make sense to you?

**Comment by m-mohr** [comment] 2020-07-08 09:36
Not yet ;-)

You already pass the data and the mask as raster data cubes and then it replaces according to the mask scalar values with the scalar replacement value. Replacing scalar values with data cubes doesn't seem to make much sense to me?! Can you further elaborate?

**Comment by clausmichele** [comment] 2020-07-08 09:42
The use case would be combine two datacubes given a boolean mask. The if process inside an apply would be good for that, but I don't know if it is possible to give datacube elements to the accept and reject fields inside the apply. I hope it's clear!

**Comment by m-mohr** [comment] 2020-07-08 09:46
Understood. What do others think? I'm thinking that might even be a separate process.

**Comment by m-mohr** [comment] 2020-07-08 09:49
Another idea: maybe, merge_cubes works for you?

**Comment by clausmichele** [comment] 2020-07-08 09:57
Maybe, but how to set the overlap_resolver?
@prateekbudhwar @przell what do you think?

**Comment by jdries** [comment] 2020-07-08 10:08
How about applying your mask first on both cubes, setting values to be masked to nodata.
And then you would not even need an overlap_resolver I believe, given that your cubes have exactly same dimensions and band names, I believe it will merge based on nodata right?

**Comment by przell** [comment] 2020-07-08 10:16
> How about applying your mask first on both cubes

It's worth a try to use two masks that fit together like a puzzle and merge them! Thanks for the thinking @jdries.

> It sounds wrong to mix data cubes and scalar values in if accept/reject parameters.

I also think that the use cases are limited where people want to mix replacements between scalars and datacubes? But still its the case for our use case to be delivered. 

> If on the other hand is likely directly working on scalar values if used in apply for example. Or it only works on data cubes, if used directly. It sounds wrong to mix data cubes and scalar values in if accept/reject parameters.

@m-mohr: The `if` description might need more clarification if it is intended to either work in apply (replacements can only be scalars) or directly on datacubes (replacements can only be datacubes)? Did I understand this intended behavior correctly?

**Comment by m-mohr** [comment] 2020-07-08 11:01
> Maybe, but how to set the overlap_resolver?

@clausmichele The idea was basically:
1. `new = merge_cubes(mask, replacement, if(x, y))` -> for each true in mask, replace with the value from replacement, otherwise set to null
2. `result = merge_cubes(data, new, if(is_nan(y), x, y))` -> for each non-null value in `new` use the value from new, otherwise use the value from data

> How about applying your mask first on both cubes, setting values to be masked to nodata.

Yes, that would also work, 2x mask and 1x merge_cubes. Not sure what is more efficient. I'd guess my example?

> And then you would not even need an overlap_resolver I believe, given that your cubes have exactly same dimensions and band names, I believe it will merge based on nodata right?

@jdries I don't think we have defined this behavior in merge_cubes. Can you quote the part that would allow that? Otherwise it's likely not working like that. Should it? (I don't think so...)

> I also think that the use cases are limited where people want to mix replacements between scalars and datacubes? But still its the case for our use case to be delivered.

@przell Can you give an example? It still seems that there's something wrong. 

> @m-mohr: The `if` description might need more clarification if it is intended to either work in apply (replacements can only be scalars) or directly on datacubes (replacements can only be datacubes)? Did I understand this intended behavior correctly?

It's not strictly illegal to set one of accept/reject as data cube and one to scalar values, but I don't see many cases where this is useful. Or what clarification are you thinking about precisely?

**Comment by jdries** [comment] 2020-07-08 11:11
Indeed, I was referring to this case:
`Data cubes with the dimensions x, y, t and bands have the same dimension labels in x,y and t, but the labels for the dimension bands are B1 and B2 for the first data cube and B2 and B3 for the second. An overlap resolver is required to resolve overlap in band B2. The merged data cube has the dimensions x, y, t and bands and the dimension bands has three dimension labels: B1, B2, B3.`
But it does require a resolver. A very basic resolver would do the trick though, like a sum that ignores nodata.

**Comment by przell** [comment] 2020-07-09 12:14
> It's not strictly illegal to set one of accept/reject as data cube and one to scalar values, but I don't see many cases where this is useful. Or what clarification are you thinking about precisely?

@m-mohr: in this case the definition of the process is ok. And we are possibly using this case ;)

**Comment by m-mohr** [comment] 2020-07-09 14:10
With the alternatives given, I think it's reasonable to keep the mask process as is and not add yet another option. If there are still other opinions or things to discuss, just comment here and we'll reopen.

**Closed by m-mohr** 2020-07-09 14:10 UTC
Labels: question
