### ISSUE TITLE
filter_temporal,  filter_bbox, ... on vector cube

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes#338] opened 2022-03-14 10:53 UTC
The filter processes like `filter_temporal`, `filter_bbox`, `filter_bands`, ... currently only accept a `raster-cube` object as input (first argument), but shouldn't we also support vector cubes as input?

**Comment by m-mohr** [comment] 2022-03-14 11:23
Sure, we need to go through all processes and check the data types. But it doesn't help to open issues for all these processes separately now. First we need to get the basics defined, then I'll go through the processes and check each of them on required changes.

Closing as duplicate of https://github.com/Open-EO/openeo-processes/issues/68 and https://github.com/Open-EO/openeo.org/issues/58

**Closed by m-mohr** 2022-03-14 11:23 UTC
